import { z } from "zod";
export const createForwarderType = z
  .object({
    shipmentId: z.string().uuid(),
    type: z.string(),
    docNumber: z.string(),
    fields : z.record(z.any()),
    schema : z.record(z.any()).optional(),
  });
const fieldsSchema = z.object({
    date: z.string(),
  place: z.string(),
  nameA: z.string(),
  addressA: z.string(),
  phoneA: z.string(),
  taxA: z.string(),
  faxA: z.string(),
  numberA: z.string(),
  numberB: z.string(),
  representA: z.string(),
  positionA: z.string(),
  nameB: z.string(),
  faxB: z.string(),
  phoneB: z.string(),
  taxB: z.string(),
  addressB: z.string(),
  representB: z.string(),
  positionB: z.string(),
  fresh: z.string(),
  freshNum: z.string(),
  fade: z.string(),
  fadeNum: z.string(),
  keep: z.string(),
  keepNum: z.string(),
  fragile: z.string(),
  fragileNum: z.string(),
  cattle: z.string(),
  cattleNum: z.string(),
  freight: z.string(),
  warehouse: z.string(),
  location: z.string(),
  transport: z.string(),
  speed: z.string(),
  roof: z.string(),
  transportNum: z.string(),
  resTime: z.string(),
  resMoney: z.string(),
  resMoneyLetter: z.string(),
  waitTime: z.string(),
  totalFee: z.string(),
  delayTime: z.string(),
  beforeTime: z.string(),
  methodA: z.string(),
  methodB: z.string(),
  freeTime: z.string(),
  nightFee: z.string(),
  holidayFee: z.string(),
  rewardFee: z.string(),
  fineFee: z.string(),
  loss: z.string(),
  peopleNum: z.string(),
  mainFeeA: z.string(),
  mainFeeB: z.string(),
  totalCost: z.string(),
  perMile: z.string(),
  boatFee: z.string(),
  conveyFee: z.string(),
  materialFee: z.string(),
  cageFee: z.string(),
  fuelFee: z.string(),
  parkFee: z.string(),
  declareFee: z.string(),
  portFee: z.string(),
  navigatorFee: z.string(),
  totalCostFee: z.string(),
  totalCostFeeLetter: z.string(),
  formA: z.string(),
  formB: z.string(),
  preventA: z.string(),
  preventB: z.string(),
  fineFor: z.string(),
  bankFee: z.string(),
  noReasonFee: z.string(),
  fromDate: z.string(),
  toDate: z.string(),
  meetDate: z.string(),
  ver: z.string(),
  rows: z.array(
    z.object({
      productName: z.string(),
      qtyA: z.string(),
      locationA: z.string(),
      timeA: z.string(),
      qtyB: z.string(),
      locationB: z.string(),
      timeB: z.string(),
      note: z.string(),
    })
  ),
  signatureA: z.string(),
  signatureB: z.string(),
});
export const getForwarderProviderListById = z.object({
  id: z.string(),
  type: z.string(),
  docNumber: z.string(),
  userId: z.string(),
  fields: fieldsSchema, 
  schema: z.record(z.any()),
  shipmentId: z.string(),
});
export type CreateForwarderType = z.TypeOf<typeof createForwarderType>;
export type GetForwarderProviderListByIdType = z.TypeOf<typeof getForwarderProviderListById>;